### ISSUE TITLE
Twitter embed option is using an unsupported API

### ISSUE THREAD

**Issue by andypiper** [astro-community/astro-embed#16]
It looks like this component is making use of an unsupported Twitter endpoint.

```
	return await safeGet(`https://cdn.syndication.twimg.com/tweet?id=${id}`);
```

Worth noting that this may change or become inaccessible at any time, so I'd encourage either using the Twitter embedded JavaScript widgets (publish.twitter.com), or a server-side option that uses the latest Twitter API v2.

**Comment by delucis** [comment]
Thanks! Using the unsupported syndication API was a conscious choice made to avoid users needing to set up API keys, but with the knowledge that the API may change as you mention. Similarly, the Twitter embedded widgets ship JavaScript (and a lot of it!) whereas these components are JavaScript-free, so very intentional decision not to use those here.
